name: Run Python Scripts

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  run-scripts:
    if: github.event_name == 'workflow_dispatch' # Only run manually for now
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Camera_images_try.py script
      run: |
        python path/to/Camera_images_try.py

    - name: Run Blog_scrap_try.py script
      run: |
        python path/to/Blog_scrap_try.py
